version: "2"
services:

# 
# Client
# Frontend webpage will run on port 3000
#
  client:
    build: ./client
    environment:
      - VUE_APP_PORT=3000
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/search-place-project
      - ./client/public:/app/search-place-project
    command: npm run serve

# 
# Server
# Backend server will run on port 8080
# with MYSQL Database on port 6603
#
  api:
    build:
      context: .
      dockerfile: ./server/container-build/web/Dockerfile
    environment:
    - MYSQL_DATABASE=dbname
    - MYSQL_USER=dbuser
    - MYSQL_PASSWORD=654321
    - MYSQL_HOST=db
    ports:
    - "8080:80"
    volumes:
    - ./server:/var/www
    depends_on:
    - db

  db:
    image: mysql:5.7
    ports:
    - "6603:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=654321
    - MYSQL_USER=dbuser
    - MYSQL_PASSWORD=654321
    - MYSQL_DATABASE=dbname
    volumes:
    - "mysql_data:/var/lib/mysql"
    - ./server/data/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  mysql_data: { driver: local }