<?php
/**
 * This file generated by Zend\Expressive\Tooling\Factory\ConfigInjector.
 *
 * Modifications should be kept at a minimum, and restricted to adding or
 * removing factory definitions; other dependency types may be overwritten
 * when regenerating this file via zend-expressive-tooling commands.
 */
 
declare(strict_types=1);

return [
    'dependencies' => [
        'factories' => [
            SearchPlace\Handler\FindCandidateHandler::class => SearchPlace\Handler\FindCandidateHandlerFactory::class,
            SearchPlace\Handler\PlaceAddingHandler::class => SearchPlace\Handler\PlaceAddingHandlerFactory::class,
            SearchPlace\Handler\SearchPlaceReadHandler::class => SearchPlace\Handler\SearchPlaceReadHandlerFactory::class,
            SearchPlace\Handler\SearchSinglePlaceHandler::class => SearchPlace\Handler\SearchSinglePlaceHandlerFactory::class,
        ],
    ],
];
